env:
  PORT: 8080
  NAMESPACE: ux-foundations
  ALLOWED_ORIGINS: http://localhost:3000,https://mongodb.design,https://staging.mongodb.design
  MONGODB_USER: adam
  MONGODB_APP_NAME: LeafyGreenAI
  VECTOR_SEARCH_INDEX_NAME: vector_index
  MONGODB_DATABASE_NAME: lgai-chatbot-rag
  AZURE_OPENAI_EMBEDDING_MODEL: text-embedding-ada-002
  AZURE_OPENAI_API_EMBEDDING_DEPLOYMENT_NAME: text-embedding-ada-002
  AZURE_OPENAI_CHAT_COMPLETION_MODEL: gpt-4.1
  AZURE_OPENAI_API_CHAT_COMPLETION_DEPLOYMENT_NAME: gpt-4.1

envSecrets:
  MONGODB_PASSWORD: lg-secrets
  MONGODB_PROJECT_URL: lg-secrets
  AZURE_OPENAI_API_KEY: lg-secrets
  AZURE_OPENAI_ENDPOINT: lg-secrets
  AZURE_OPENAI_API_EMBEDDING_DEPLOYMENT_URL: lg-secrets
  AZURE_OPENAI_API_CHAT_COMPLETION_DEPLOYMENT_URL: lg-secrets

# Pod resources
replicaCount: 2
resources:
  limits:
    cpu: 2
    memory: 2Gi
  requests:
    cpu: 1000m
    memory: 1Gi

# Health checks
probes:
  enabled: true
  path: /health
  headers: {}
  liveness:
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 2
    successThreshold: 1
    failureThreshold: 3
  readiness:
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 2
    successThreshold: 1
    failureThreshold: 3
