/**
 * All `@azublue-ui/*` packages as of November 2024 that can be identified in
 * import declarations to determine if a codemod should be run on them.
 */
export const AzuBluePackage = {
  A11y: '@azublue-ui/a11y',
  Avatar: '@azublue-ui/avatar',
  Badge: '@azublue-ui/badge',
  Banner: '@azublue-ui/banner',
  Box: '@azublue-ui/box',
  Button: '@azublue-ui/button',
  Callout: '@azublue-ui/callout',
  Card: '@azublue-ui/card',
  Checkbox: '@azublue-ui/checkbox',
  Chip: '@azublue-ui/chip',
  Code: '@azublue-ui/code',
  Combobox: '@azublue-ui/combobox',
  ConfirmationModal: '@azublue-ui/confirmation-modal',
  Copyable: '@azublue-ui/copyable',
  DatePicker: '@azublue-ui/date-picker',
  DateUtils: '@azublue-ui/date-utils',
  Descendants: '@azublue-ui/descendants',
  Emotion: '@azublue-ui/emotion',
  EmptyState: '@azublue-ui/empty-state',
  ExpandableCard: '@azublue-ui/expandable-card',
  FormField: '@azublue-ui/form-field',
  FormFooter: '@azublue-ui/form-footer',
  GuideCue: '@azublue-ui/guide-cue',
  Hooks: '@azublue-ui/hooks',
  Icon: '@azublue-ui/icon',
  IconButton: '@azublue-ui/icon-button',
  InfoSprinkle: '@azublue-ui/info-sprinkle',
  InlineDefinition: '@azublue-ui/inline-definition',
  InputOption: '@azublue-ui/input-option',
  AzuBlueProvider: '@azublue-ui/leafygreen-provider',
  Lib: '@azublue-ui/lib',
  LoadingIndicator: '@azublue-ui/loading-indicator',
  Logo: '@azublue-ui/logo',
  MarketingModal: '@azublue-ui/marketing-modal',
  Menu: '@azublue-ui/menu',
  Modal: '@azublue-ui/modal',
  NumberInput: '@azublue-ui/number-input',
  Pagination: '@azublue-ui/pagination',
  Palette: '@azublue-ui/palette',
  PasswordInput: '@azublue-ui/password-input',
  Pipeline: '@azublue-ui/pipeline',
  Polymorphic: '@azublue-ui/polymorphic',
  Popover: '@azublue-ui/popover',
  Portal: '@azublue-ui/portal',
  RadioBoxGroup: '@azublue-ui/radio-box-group',
  RadioGroup: '@azublue-ui/radio-group',
  Ripple: '@azublue-ui/ripple',
  SearchInput: '@azublue-ui/search-input',
  SegmentedControl: '@azublue-ui/segmented-control',
  Select: '@azublue-ui/select',
  SideNav: '@azublue-ui/side-nav',
  SkeletonLoader: '@azublue-ui/skeleton-loader',
  SplitButton: '@azublue-ui/split-button',
  Stepper: '@azublue-ui/stepper',
  Table: '@azublue-ui/table',
  Tabs: '@azublue-ui/tabs',
  TestingLib: '@azublue-ui/testing-lib',
  TextArea: '@azublue-ui/text-area',
  TextInput: '@azublue-ui/text-input',
  Toast: '@azublue-ui/toast',
  Toggle: '@azublue-ui/toggle',
  Tokens: '@azublue-ui/tokens',
  Tooltip: '@azublue-ui/tooltip',
  Typography: '@azublue-ui/typography',
} as const;
export type AzuBluePackage = (typeof AzuBluePackage)[keyof typeof AzuBluePackage];
