name: React 17

on:
  merge_group:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  react17:
    name: Test in React 17
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.0
          # no cache because we want to test installs from scratch
          cache: false

      - name: Setup Node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install node-gyp
        run: pnpm add --global node-gyp

      - name: Init React 17 environment
        run: node ./scripts/react17/init.mjs

      - name: Install packages
        run: pnpm install --prefer-offline

      - name: Build packages
        run: pnpm build

      - name: Run tests in React 17
        run: pnpm run test --react17
