name: React 17

on:
  merge_group:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  react17:
    name: Test in React 17
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.0

      - name: Setup Node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install node-gyp
        run: pnpm add --global node-gyp

      - name: Install @lg-tools/test dependencies
        run: pnpm install --prefer-offline --filter="@lg-tools/test"

      - name: Build @lg-tools/test
        run: pnpm turbo run build tsc --filter="@lg-tools/test"

      - name: Install testing tools for React 17
        run: npx ts-node tools/test/scripts/install-react17.ts

      - name: Build packages
        run: pnpm build

      - name: Run tests in React 17
        run: pnpm run test --react17

      - name: Upload pnpm-lock.yaml
        uses: actions/upload-artifact@v4
        with:
          name: pnpm-lock
          path: pnpm-lock.yaml
          retention-days: 1
